version: '3.8'

services:
  server:
    build: 
      context: .
      dockerfile: server/Dockerfile
      args:
        ALLOWED_ORIGINS: "http://client:8080"
    ports:
      - "9090:9090"
    networks:
      - offshore-proxy-secure-network

  client:
    build: 
      context: .
      dockerfile: client/Dockerfile
      args:
        OFFSHORE_PROXY_URL: "http://server:9090"
    ports:
      - "8080:8080"
    depends_on:
      - server
    networks:
      - offshore-proxy-secure-network


networks:
  offshore-proxy-secure-network:
    driver: bridge